composer.json
src/GraphQL/Types/BeamClaimType.php
src/GraphQL/Types/BeamType.php
src/Models/Laravel/Beam.php
src/Models/Laravel/Traits/EagerLoadSelectFields.php
testbench.yaml
tests/Feature/GraphQL/Queries/GetBeamTest.php
tests/Feature/GraphQL/Queries/GetBeamsTest.php
tests/Feature/GraphQL/Resources/GetBeam.graphql
tests/Feature/GraphQL/TestCaseGraphQL.php

Bugfixes and updates for non-selectable fields and blockchain update.
Requires: https://github.com/enjin/platform-core/pull/65

Exclude single use codes and QRs from BeamClaim type when not authenticated.

---

lang/en/type.php
src/GraphQL/Types/AttributeType.php
src/GraphQL/Types/BeamClaimType.php
tests/Feature/GraphQL/Resources/GetClaims.graphql

Enhancement
___
This PR introduces an 'attributes' field to the BeamClaimType. The main changes include:
- Addition of a new 'AttributeType' class in the GraphQL types.
- Addition of 'attributes' field in the 'BeamClaimType' class.
- Update of the 'GetClaims' GraphQL query in the tests to include the 'attributes' field.
___
<details> <summary>files:</summary>
- `lang/en/type.php`: Added a new 'attribute.description' field in the language file for English.
- `src/GraphQL/Types/AttributeType.php`: Introduced a new 'AttributeType' class with 'key' and 'value' fields.
- `src/GraphQL/Types/BeamClaimType.php`: Added an 'attributes' field of type 'AttributeType' to the 'BeamClaimType' class.
- `tests/Feature/GraphQL/Resources/GetClaims.graphql`: Updated the 'GetClaims' GraphQL query in the tests …

Add Attributes Field to BeamClaimType

---

database/migrations/2024_02_26_013401_add_idempotency_key_to_beam_claims_table.php
src/BeamServiceProvider.php
src/GraphQL/Mutations/ClaimBeamMutation.php
src/GraphQL/Types/BeamClaimType.php
src/Jobs/ClaimBeam.php
src/Models/Laravel/BeamClaim.php
src/Services/BeamService.php
tests/Feature/GraphQL/Mutations/ClaimBeamTest.php
tests/Feature/GraphQL/Resources/GetClaims.graphql
tests/Feature/GraphQL/Resources/GetPendingClaims.graphql

enhancement
___
- Adds support for idempotency key in beam claims to prevent duplicate claims.
- Introduces a new column `idempotency_key` in the `beam_claims` table.
- Updates `ClaimBeamMutation` to handle idempotency key, including checks for existing claims with the same key.
- Adds `idempotencyKey` field to `BeamClaimType` and includes it in relevant GraphQL queries.
- Modifies `BeamService` and related jobs to support idempotency key during beam claim processing.
- Includes tests to verify the functionality of claiming beams with an idempotency key.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>8 files</summary><table>
<tr>
<td>
<details> …

[PLA-136] Add idempotencyKey to ClaimBeam Mutation

---

src/GraphQL/Mutations/ClaimBeamMutation.php
src/GraphQL/Queries/GetBeamQuery.php
src/Rules/SingleUseCodeExist.php
tests/Feature/GraphQL/Queries/GetBeamTest.php

enhancement, tests
___
- Enhanced the `SingleUseCodeExist` rule to support conditional claimability checks, improving the flexibility of beam claim validations.
- Added new tests to verify the functionality of retrieving beams with single-use codes, ensuring robustness.
___
<tr>
<td>
<details>
<summary><strong>ClaimBeamMutation.php</strong><dd><code>Enhance Single Use Code Validation for Claiming</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/GraphQL/Mutations/ClaimBeamMutation.php
<li>Added a boolean parameter to <code>SingleUseCodeExist</code> constructor to support <br>conditional claimability …

[PLA-1708] Remove validation on GetBeam

---

composer.json
lang/en/mutation.php
src/GraphQL/Queries/GetClaimsQuery.php
src/Models/Laravel/BeamClaim.php
src/Models/Laravel/Traits/HasSingleUseCodeScope.php
tests/Feature/GraphQL/Queries/GetClaimsTest.php
tests/Feature/GraphQL/Resources/GetClaims.graphql

Enhancement, Tests
___
- Added `singleUseCodes` argument to `GetClaims` query and implemented filtering logic.
- Created `HasSingleUseCodeScope` trait for filtering by single use code and integrated it into the `BeamClaim` model.
- Added translation for `single_use_code` argument in `claim_beam`.
- Added test for `singleUseCodes` filter in `GetClaims` query.
- Added `fix` script for PHP CS Fixer in `composer.json`.
- Added `singleUseCodes` argument to `GetClaims` GraphQL query.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>mutation.php</strong><dd><code>Add translation for single use code argument.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

[PLA-1778] Add singleUseCodes filter to GetClaims query.

---

src/Rules/CanClaim.php
tests/Feature/GraphQL/Mutations/ClaimBeamTest.php

Bug fix, Tests
___
- Added a check in `CanClaim.php` to prevent claiming single-use beams from multi-use codes.
- Introduced a new test in `ClaimBeamTest.php` to verify that single-use beams cannot be claimed from multi-use codes.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>CanClaim.php</strong><dd><code>Prevent claiming single-use beams from multi-use codes.</code>&nbsp; &nbsp; </dd></summary>
<hr>
src/Rules/CanClaim.php
<li>Added a check to prevent claiming single-use beams from multi-use <br>codes.<br> <li> Added a condition to fail validation if a single-use beam is detected <br>in a multi-use context.<br>
</details>
</td>
<td><a …

[PLA-1780] Ensure Beams can't be claimed from base code when set to Single Use

---

src/GraphQL/Mutations/ClaimBeamMutation.php
src/GraphQL/Queries/GetPendingClaimsQuery.php
src/Models/Laravel/BeamClaim.php
src/Models/Laravel/Traits/HasCodeScope.php
src/Models/Laravel/Traits/HasSingleUseCodeScope.php
src/Rules/BeamExists.php
src/Rules/CanClaim.php
src/Rules/VerifySignedMessage.php
src/Services/BeamService.php
tests/Feature/GraphQL/Queries/GetPendingClaimsTest.php

Enhancement, Tests
___
- Refactored various parts of the codebase to handle single-use codes using the new `BeamService::getSingleUseCodeData` method.
- Enhanced validation rules to support single-use codes.
- Added a new test case to verify the functionality of pending claims using single-use codes.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><details><summary>9 files</summary><table>
<tr>
<td>
<details>
<summary><strong>ClaimBeamMutation.php</strong><dd><code>Refactor single-use code handling in ClaimBeamMutation</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/GraphQL/Mutations/ClaimBeamMutation.php
<li>Replaced decryption logic with <code>BeamService::getSingleUseCodeData</code> for …

[PLA-1861] Updates and tweaks for dealing with single use codes.

---

src/BeamServiceProvider.php
src/Package.php

Enhancement, Tests
___
- Enhanced `BeamServiceProvider` to set the path for `BeamPackage` during unit tests.
- Simplified `Package` class by removing the `getAutoloader` method and extending `CorePackage`.
___
<tr>
<td>
<details>
<summary><strong>BeamServiceProvider.php</strong><dd><code>Enhance BeamServiceProvider with BeamPackage path for tests</code></dd></summary>
<hr>
src/BeamServiceProvider.php
<li>Added import for <code>BeamPackage</code>.<br> <li> Added conditional path setting for <code>BeamPackage</code> during unit tests.<br>
</details>
</td>
<td><a href="https://github.com/enjin/platform-beam/pull/79/files#diff-f80ec4f5b8eb2dc8bb7dc8a8f97ef0d7f …

[PLA-1693] Improved local testing.

---

src/GraphQL/Queries/GetBeamQuery.php
src/GraphQL/Queries/GetBeamsQuery.php
src/GraphQL/Types/BeamType.php
tests/Feature/GraphQL/Queries/GetBeamTest.php
tests/Feature/GraphQL/Queries/GetBeamsTest.php

Enhancement
___
- Removed the implementation of `PlatformPublicGraphQlOperation` interface from `GetBeamQuery` and `GetBeamsQuery` classes.
- Adjusted class definitions to make the beam APIs private.
___
<tr>
<td>
<details>
<summary><strong>GetBeamQuery.php</strong><dd><code>Make GetBeamQuery class private by removing interface</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/GraphQL/Queries/GetBeamQuery.php
<li>Removed implementation of <code>PlatformPublicGraphQlOperation</code> interface.<br> <li> Adjusted class definition accordingly.<br>
</details>
</td>
<td><a href="https://github.com/enjin/platform-beam/pull/85/files#diff-94c4eff1889e3d1b2 …

[PLA-1891] Hide sensitive attributes from beam APIs

---

src/GraphQL/Types/BeamType.php
tests/Feature/GraphQL/Queries/GetBeamTest.php
tests/Feature/GraphQL/Queries/GetBeamsTest.php

enhancement
___
- Removed the 'excludeFrom' attribute for the 'code' and 'qr' fields in the `BeamType` class to simplify the field definitions.
- This change ensures that the 'code' and 'qr' fields are now included in the 'GetBeam' and 'GetBeams' queries.
___
<tr>
<td>
<details>
<summary><strong>BeamType.php</strong><dd><code>Simplify BeamType fields by removing 'excludeFrom' attributes</code></dd></summary>
<hr>
src/GraphQL/Types/BeamType.php
<li>Removed 'excludeFrom' attribute for 'code' and 'qr' fields in the <br>BeamType class.<br> <li> Simplified the fields definition by excluding unnecessary attributes.<br>
</details>
</td>
<td><a …

[PLA-1899] Expose qr and code for get beam

---

src/GraphQL/Mutations/CreateBeamMutation.php
tests/Feature/GraphQL/Mutations/CreateBeamTest.php

Bug fix, Tests
___
- Removed validation rules `TokensDoNotExistInCollection` and `TokenUploadNotExistInCollection` from `CreateBeamMutation`.
- Updated conditional logic to handle cases where these validation rules were previously applied.
- Removed corresponding tests for token existence in collection validation from `CreateBeamTest`.
- Simplified the test for invalid file upload in `CreateBeamTest`.
___
<tr>
<td>
<details>
<summary><strong>CreateBeamMutation.php</strong><dd><code>Remove redundant token existence validation rules</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/GraphQL/Mutations/CreateBeamMutation.php …

[PLA-1896] Fix validation create beam on mint on demand

---

composer.json
src/Commands/BatchProcess.php

Bug fix, Enhancement
___
- Fixed a bug in `BatchProcess.php` by conditionally appending 'V1010' to the method name in the `encoded_data` field based on the `isRunningLatest()` function.
- Updated `composer.json` to:
- Include PHP version ^8.3.
- Downgrade `rebing/graphql-laravel` dependency version.
- Adjust versions for `laravel/pint` and `nunomaduro/collision` in `require-dev`.
___
<tr>
<td>
<details>
<summary><strong>BatchProcess.php</strong><dd><code>Conditional method name modification in transaction encoding</code></dd></summary>
<hr>
src/Commands/BatchProcess.php
<li>Modified the <code>encoded_data</code> field to append 'V1010' to the method name …

[PLA-1907] Fixes Beam transactions

---

src/Commands/BatchProcess.php

Bug fix, Enhancement
___
- Added import for `BatchMintMutation` to handle specific batch minting logic.
- Updated the `processBatch` method to include conditional logic for `BatchMint` encoding.
- Fixed an encoding issue related to the `php-scale-codec` library when using `BatchMint`.
- Ensured transactions are correctly stored with the appropriate encoded data.
___
<tr>
<td>
<details>
<summary><strong>BatchProcess.php</strong><dd><code>Fix and enhance batch processing for beam encoding</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Commands/BatchProcess.php
<li>Added import for <code>BatchMintMutation</code>.<br> <li> Updated …

[PLA-1915] Fixes beams encoding

---

src/GraphQL/Types/BeamScanType.php

Bug fix
___
- Fixed a typo in the translation string key for `walletPublicKey` description in `BeamScanType.php`.
___
<tr>
<td>
<details>
<summary><strong>BeamScanType.php</strong><dd><code>Fix typo in translation string key for walletPublicKey</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/GraphQL/Types/BeamScanType.php
<li>Fixed a typo in the translation string key for <code>walletPublicKey</code> <br>description.<br>
</details>
</td>
<td><a href="https://github.com/enjin/platform-beam/pull/91/files#diff-5d73f7589d85484cc692a8d2da7ca0bc7178a0b1554925d1cfd6eec3ea39b385">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr> …

[PLA-1414] Fix typo in translation string key.

---

lang/en/validation.php
src/Rules/MaxTokenCount.php
src/Rules/MaxTokenSupply.php
tests/Feature/GraphQL/Mutations/CreateBeamTest.php
tests/Feature/GraphQL/Mutations/UpdateBeamTest.php

Enhancement, Bug fix, Tests
___
- Refactored the `MaxTokenCount` rule to ensure unique token validation and efficient processing using `LazyCollection`.
- Simplified the `MaxTokenSupply` rule by removing unnecessary dependencies and ensuring validation against the total circulating supply.
- Updated validation messages to specify limits for unique tokens.
- Enhanced test coverage for `CreateBeam` and `UpdateBeam` mutations to reflect new validation logic and messages.
___
<tr>
<td>
<details>
<summary><strong>validation.php</strong><dd><code>Update validation message for max token supply</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

[PLA-1939] Refactor max token count and supply rule

---

src/Listeners/RemoveClaimToken.php

enhancement
___
- Enhanced the `RemoveClaimToken` listener by adding checks for the existence of a collection before proceeding with token operations.
- Optimized the logic for handling token and beam claims, improving performance and readability.
- Replaced the `each` method with more efficient query operations to handle beam claims and cache decrements.
- Improved the cache decrement logic by directly working with beam codes.
___
<tr>
<td>
<details>
<summary><strong>RemoveClaimToken.php</strong><dd><code>Optimize and enhance the RemoveClaimToken listener logic</code>&nbsp; </dd></summary>
<hr>
src/Listeners/RemoveClaimToken.php
<li>Added checks for …

[PLA-1970] Optimize remove claim token listener

---

src/Commands/BatchProcess.php

enhancement
___
- Enhanced the batch processing logic by introducing a check for collection approval using the `CollectionService`.
- Modified the logic for determining the `source` in transfer parameters, utilizing a match expression for better clarity and functionality.
- Added a new import for `CollectionService` to support the new approval check functionality.
___
<tr>
<td>
<details>
<summary><strong>BatchProcess.php</strong><dd><code>Enhance batch processing with collection approval check</code>&nbsp; &nbsp; </dd></summary>
<hr>
src/Commands/BatchProcess.php
<li>Added import for <code>CollectionService</code>.<br> <li> Introduced a new variable …

Check wallet daemon approval

---

src/Jobs/ClaimBeam.php
src/Listeners/PauseBeam.php
src/Rules/CanClaim.php
tests/Feature/GraphQL/Mutations/ClaimBeamTest.php

Enhancement, Tests
___
- Enhanced the claim query in `ClaimBeam` to handle frozen collections, allowing claims to be processed correctly based on the collection's state.
- Improved the `PauseBeam` listener to incorporate logic that checks for claim types before pausing beams, ensuring correct handling of beams with different claim types.
- Updated the `CanClaim` rule to adjust validation logic and remaining claims calculation when collections are frozen, ensuring accurate claim processing.
- Added comprehensive tests in `ClaimBeamTest` to verify the behavior of claims when collections are frozen, covering various scenarios and claim types.
___
<tr>
<td> …

[PLA-1965] Fix freeze collection

---

src/Models/Laravel/Beam.php

enhancement
___
- Refactored the `probabilities` method in `Beam.php` to enhance the format of the probabilities data.
- Introduced a local variable to store probabilities and converted arrays to objects for better structure.
___
<tr>
<td>
<details>
<summary><strong>Beam.php</strong><dd><code>Refactor probabilities method for improved data formatting</code></dd></summary>
<hr>
src/Models/Laravel/Beam.php
<li>Refactored the <code>probabilities</code> method to improve data formatting.<br> <li> Introduced a local variable <code>$probabilities</code> for cleaner code.<br> <li> Converted probability arrays to objects for <code>ft</code>, <code>nft</code>, …

[PLA-2078] Correct probabilities format

---

src/Services/BeamService.php

Bug fix
___
- Fixed a bug in the `claim` method of `BeamService` where the `singleUseCode` was incorrectly assigned.
- Ensured that the `singleUseCode` is set directly from the input `code` for proper functionality.
___
<tr>
<td>
<details>
<summary><strong>BeamService.php</strong><dd><code>Fix assignment of single-use code variable</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Services/BeamService.php
<li>Fixed assignment of <code>singleUseCode</code> to use the correct variable.<br> <li> Ensured <code>singleUseCode</code> is set to the input <code>code</code> instead of …

[PLA-2079] Fix single use code

---

src/Support/ClaimProbabilities.php

bug_fix
___
- Fixed a potential crash in the `getProbabilities` method by allowing the `code` parameter to be nullable and adding a check for empty values.
- Ensured that an empty array is returned when `code` is empty, preventing further processing and potential errors.
___
<tr>
<td>
<details>
<summary><strong>ClaimProbabilities.php</strong><dd><code>Fix crash by handling empty code in getProbabilities</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Support/ClaimProbabilities.php
<li>Modified <code>getProbabilities</code> method to accept nullable string.<br> <li> Added a check for empty <code>code</code> to return an empty array.<br> …

[PLA-2080] Check for empty values

---

src/Jobs/DispatchCreateBeamClaimsJobs.php

bug_fix, enhancement
___
- Added a check to ensure the beam collection exists before proceeding with job execution.
- Implemented logging to capture errors when the beam collection is not found, aiding in debugging and error tracking.
- Introduced an early return to prevent further execution if the beam collection is missing, enhancing the robustness of the job handling.
___
<tr>
<td>
<details>
<summary><strong>DispatchCreateBeamClaimsJobs.php</strong><dd><code>Add logging and validation for beam collection existence</code>&nbsp; </dd></summary>
<hr>
src/Jobs/DispatchCreateBeamClaimsJobs.php
<li>Added logging for missing beam collection.<br> <li> Implemented …

[PLA-2082] Check collection validity

---

src/Events/BeamClaimPending.php
src/Models/Laravel/Beam.php
src/Rules/BeamExists.php

Enhancement, Bug fix
___
- Added `formatFtTokenIds` method to handle token ID ranges.
- Updated `probabilities` attribute to use formatted token IDs.
- Fixed minor formatting issues in comments and annotations.
- Introduced `HasIntegerRanges` trait to `Beam` model.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Formatting</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>BeamClaimPending.php</strong><dd><code>Fix comment formatting in BeamClaimPending</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Events/BeamClaimPending.php
- Fixed a minor formatting issue in a comment.
</details>
</td>
<td><a …

[PLA-2125] Fix probablities format
